namespace OpenControls.Examples;

public static class DemoMarkers
{
    public static readonly string[] Markers =
    {
        "Help",
        "Configuration",
        "Configuration/Backend Flags",
        "Configuration/Style, Fonts",
        "Configuration/Capture, Logging",
        "Window options",
        "Menu",
        "Menu/File",
        "Menu/Examples",
        "Menu/Tools",
        "Widgets/Basic",
        "Widgets/Basic/Button",
        "Widgets/Basic/Checkbox",
        "Widgets/Basic/RadioButton",
        "Widgets/Basic/Buttons (Colored)",
        "Widgets/Basic/Buttons (Repeating)",
        "Widgets/Basic/InputText",
        "Widgets/Basic/InputInt, InputFloat",
        "Widgets/Basic/DragInt, DragFloat",
        "Widgets/Basic/SliderInt, SliderFloat",
        "Widgets/Basic/SliderAngle",
        "Widgets/Basic/Slider (enum)",
        "Widgets/Basic/ColorEdit3, ColorEdit4",
        "Widgets/Basic/Combo",
        "Widgets/Basic/ListBox",
        "Widgets/Bullets",
        "Widgets/Collapsing Headers",
        "Widgets/Color",
        "Widgets/Color/ColorEdit",
        "Widgets/Color/ColorEdit (HSV, with Alpha)",
        "Widgets/Color/ColorEdit (float display)",
        "Widgets/Color/ColorButton (with Picker)",
        "Widgets/Color/ColorButton (with custom Picker popup)",
        "Widgets/Color/ColorButton (simple)",
        "Widgets/Color/ColorPicker",
        "Widgets/Combo",
        "Widgets/Data Types",
        "Widgets/Data Types/Drags",
        "Widgets/Data Types/Sliders",
        "Widgets/Data Types/Inputs",
        "Widgets/Disable Blocks",
        "Widgets/Drag and drop",
        "Widgets/Drag and drop/Standard widgets",
        "Widgets/Drag and drop/Copy-swap items",
        "Widgets/Drag and Drop/Drag to reorder items (simple)",
        "Widgets/Drag and Drop/Tooltip at target location",
        "Widgets/Drag and Slider Flags",
        "Widgets/Fonts",
        "Widgets/Images",
        "Widgets/Images/Textured buttons",
        "Widgets/List Boxes",
        "Widgets/Multi-component Widgets",
        "Widgets/Plotting",
        "Widgets/Progress Bars",
        "Widgets/Querying Item Status (Edited,Active,Hovered etc.)",
        "Widgets/Querying Window Status (Focused,Hovered etc.)",
        "Widgets/Selectables",
        "Widgets/Selectables/Basic",
        "Widgets/Selectables/Rendering more items on the same line",
        "Widgets/Selectables/In Tables",
        "Widgets/Selectables/Grid",
        "Widgets/Selectables/Alignment",
        "Widgets/Selection State & Multi-Select",
        "Widgets/Selection State/Single-Select",
        "Widgets/Selection State/Multi-Select (manual/simplified, without BeginMultiSelect)",
        "Widgets/Selection State/Multi-Select",
        "Widgets/Selection State/Multi-Select (with clipper)",
        "Widgets/Selection State/Multi-Select (with deletion)",
        "Widgets/Selection State/Multi-Select (dual list box)",
        "Widgets/Selection State/Multi-Select (in a table)",
        "Widgets/Selection State/Multi-Select (checkboxes)",
        "Widgets/Selection State/Multi-Select (multiple scopes)",
        "Widgets/Selection State/Multi-Select (trees)",
        "Widgets/Selection State/Multi-Select (advanced)",
        "Widgets/Tabs",
        "Widgets/Tabs/Basic",
        "Widgets/Tabs/Advanced & Close Button",
        "Widgets/Tabs/TabItemButton & Leading-Trailing flags",
        "Widgets/Text",
        "Widgets/Text/Colored Text",
        "Widgets/Text/Font Size",
        "Widgets/Text/Word Wrapping",
        "Widgets/Text/UTF-8 Text",
        "Widgets/Text Filter",
        "Widgets/Text Input",
        "Widgets/Text Input/Multi-line Text Input",
        "Widgets/Text Input/Filtered Text Input",
        "Widgets/Text Input/Password input",
        "Widgets/Text Input/Completion, History, Edit Callbacks",
        "Widgets/Text Input/Resize Callback",
        "Widgets/Text Input/Eliding, Alignment",
        "Widgets/Text Input/Miscellaneous",
        "Widgets/Tooltips",
        "Widgets/Tree Nodes",
        "Widgets/Tree Nodes/Basic trees",
        "Widgets/Tree Nodes/Hierarchy lines",
        "Widgets/Tree Nodes/Advanced, with Selectable nodes",
        "Widgets/Vertical Sliders",
        "Widgets",
        "Layout",
        "Layout/Child windows",
        "Layout/Widgets Width",
        "Layout/Basic Horizontal Layout",
        "Layout/Basic Horizontal Layout/SameLine",
        "Layout/Basic Horizontal Layout/SameLine (with offset)",
        "Layout/Basic Horizontal Layout/SameLine (more)",
        "Layout/Basic Horizontal Layout/Dummy",
        "Layout/Basic Horizontal Layout/Manual wrapping",
        "Layout/Groups",
        "Layout/Text Baseline Alignment",
        "Layout/Scrolling",
        "Layout/Scrolling/Vertical",
        "Layout/Scrolling/Horizontal",
        "Layout/Scrolling/Horizontal (more)",
        "Layout/Scrolling/Horizontal contents size demo window",
        "Layout/Text Clipping",
        "Layout/Overlap Mode",
        "Popups",
        "Popups/Popups",
        "Popups/Context menus",
        "Popups/Modals",
        "Popups/Menus inside a regular window",
        "Tables",
        "Tables/Basic",
        "Tables/Borders, background",
        "Tables/Resizable, stretch",
        "Tables/Resizable, fixed",
        "Tables/Resizable, mixed",
        "Tables/Reorderable, hideable, with headers",
        "Tables/Padding",
        "Tables/Explicit widths",
        "Tables/Vertical scrolling, with clipping",
        "Tables/Horizontal scrolling",
        "Tables/Columns flags",
        "Tables/Columns widths",
        "Tables/Nested tables",
        "Tables/Row height",
        "Tables/Outer size",
        "Tables/Background color",
        "Tables/Tree view",
        "Tables/Item width",
        "Tables/Custom headers",
        "Tables/Angled headers",
        "Tables/Context menus",
        "Tables/Synced instances",
        "Tables/Sorting",
        "Tables/Advanced",
        "Columns (legacy API)",
        "Columns (legacy API)/Basic",
        "Columns (legacy API)/Borders",
        "Columns (legacy API)/Mixed items",
        "Columns (legacy API)/Word-wrapping",
        "Columns (legacy API)/Horizontal Scrolling",
        "Columns (legacy API)/Tree",
        "Inputs & Focus",
        "Inputs & Focus/Inputs",
        "Inputs & Focus/Outputs",
        "Inputs & Focus/Outputs/WantCapture override",
        "Inputs & Focus/Shortcuts",
        "Inputs & Focus/Mouse Cursors",
        "Inputs & Focus/Tabbing",
        "Inputs & Focus/Focus from code",
        "Inputs & Focus/Dragging",
        "Tools/About OpenControls",
        "Tools/Style Editor",
        "Examples/Menu",
        "Examples/Menu/Options",
        "Examples/Menu/Colors",
        "Examples/Menu/Append to an existing menu",
        "Examples/Console",
        "Examples/Log",
        "Examples/Simple layout",
        "Examples/Property Editor",
        "Examples/Long text display",
        "Examples/Auto-resizing window",
        "Examples/Constrained Resizing window",
        "Examples/Simple Overlay",
        "Examples/Manipulating window titles",
        "Examples/Custom Rendering",
        "Examples/Assets Browser",
    };
}
